# Generated by Django 3.2.7 on 2021-11-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller', models.BooleanField(default=False)),
                ('Buyer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('about', models.TextField(max_length=500, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.roles')),
            ],
        ),
    ]
