# Generated by Django 3.2.7 on 2021-11-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='role',
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.topic')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.people')),
            ],
        ),
    ]
