# Generated by Django 3.2.7 on 2021-11-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_post_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.BooleanField(default=False)),
                ('silver', models.BooleanField(default=False)),
                ('bronze', models.BooleanField(default=True)),
                ('amount', models.IntegerField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.people')),
            ],
        ),
    ]
