# Generated by Django 3.2.7 on 2021-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20211120_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posts',
        ),
    ]
