# Generated by Django 3.2.7 on 2021-11-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_remove_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.post'),
            preserve_default=False,
        ),
    ]
