# Generated by Django 3.2.7 on 2021-11-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_auto_20211120_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='topics',
        ),
    ]
