# Generated by Django 3.2.7 on 2021-11-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_remove_comments_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.comments'),
            preserve_default=False,
        ),
    ]
