# Generated by Django 3.2.7 on 2021-11-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_remove_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.post'),
            preserve_default=False,
        ),
    ]
