# Generated by Django 3.2.7 on 2021-11-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
