# Generated by Django 3.2.7 on 2021-11-23 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0019_auto_20211123_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='owner',
        ),
        migrations.DeleteModel(
            name='roles',
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='finance',
        ),
        migrations.DeleteModel(
            name='people',
        ),
    ]
